### ISSUE TITLE
Custom non-English keywords are not recognized

### ISSUE THREAD

**Issue by mdks2010** [robocorp/robotframework-lsp#530] opened 2021-12-20 14:18 UTC
No keyword with name 'XXX' found.

Custom non-English keywords are not recognized, hope to provide support

**Comment by fabioz** [comment] 2021-12-21 11:14
The code below does work for me:

```
*** Keywords ***
Some Kéywórd with áccênts


*** Tasks ***
Minimal task
    Some Kéywórd with áccênts
```

So, can you give more info on how to reproduce that?

**Comment by fabioz** [comment] 2021-12-21 11:15
@mdks2010 it'd be nice if you could attach some sample code to the issue where this can be reproduced...

**Comment by mdks2010** [comment] 2021-12-22 14:50
I found a solution. After adding the following settings in the custom keyword file, it was resolved.

import sys

sys.path.append(r'file path')

**Comment by mdks2010** [comment] 2021-12-22 15:11
Excuse me, where can I set the pycharm console to directly output log? After the current execution is completed, every time I view the details through log.html in the results folder, it is a bit inconvenient.

I tried adding   log   ${result}   to the robot file, but it didn't work.

Can you provide an example of setting in the help file? Thanks!

**Comment by fabioz** [comment] 2021-12-22 16:24
If you use the `Log to console` keyword instead of `Log`, it should do what you want...

Closing as the issue was related to the `PYTHONPATH` and not due to unicode.

**Closed by fabioz** 2021-12-22 16:24 UTC
Labels: enhancement, robotframework-ls
