### ISSUE TITLE
run/debug buttons don't appear if there's comments under the `*** Test Cases***` title

### ISSUE THREAD

**Issue by DetachHead** [robocorp/robotframework-lsp#440] opened 2021-09-06 05:40 UTC
**Screenshots**
![image](https://user-images.githubusercontent.com/57028336/132165902-e2109b87-5df1-4777-918b-76a520936e15.png)
![image](https://user-images.githubusercontent.com/57028336/132165919-360dadf1-e58e-414d-9aa5-c5d789041314.png)

**Versions:**
 - OS: windows 10
 - Robot Framework Version: 4.1
 - Robot Framework Language Server Version: 0.21.0
 - Client Version: vscode 1.59.1

**Comment by fabioz** [comment] 2021-09-06 17:48
This is a duplicate of https://github.com/robocorp/robotframework-lsp/issues/438 and has already been fixed (I'll provide a new release with the fix either later today or tomorrow).

**Closed by fabioz** 2021-09-06 17:48 UTC
Labels: bug, robocorp-code
