### ISSUE TITLE
Debug locks up on next run if you stop it before completing.

### ISSUE THREAD

**Issue by ericRobocorp** [robocorp/robotframework-lsp#719] opened 2022-08-08 14:23 UTC
**Describe the bug**
If I run Debug and stop it before the process completes, then I run debug again it starts but then gets stuck.  I have to stop it then start again to get it to run.

**To Reproduce**
1. Have a breakpoint
2. Run Debug
3. At breakpoint, stop the debug session
4. Run the debug session again

**Expected behavior**
Second debug session should continue without failing.

**Versions:**
 - OS: Mac 12.5
 - Robot Framework Version: 11.3.0
 - Robot Framework Language Server Version: 0.49.0
 - Client Version: Version: 1.70.0 (Universal)
Commit: da76f93349a72022ca4670c1b84860304616aaa2
Date: 2022-08-04T04:38:55.829Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Darwin x64 21.6.0

"Worked" are from the session I let the debug session complete till the end.  The others are from me stopping the debug at a breakpoint then trying to run it again.
[worked.dap.53512.log](https://github.com/robocorp/robotframework-lsp/files/9282470/worked.dap.53512.log)
[worked.pydevd.53527.log](https://github.com/robocorp/robotframework-lsp/files/9282471/worked.pydevd.53527.log)
[worked.robot.53527.log](https://github.com/robocorp/robotframework-lsp/files/9282472/worked.robot.53527.log)
[filename.dap.54590.log](https://github.com/robocorp/robotframework-lsp/files/9282475/filename.dap.54590.log)
[filename.dap.54764.log](https://github.com/robocorp/robotframework-lsp/files/9282477/filename.dap.54764.log)
[filename.pydevd.54604.log](https://github.com/robocorp/robotframework-lsp/files/9282478/filename.pydevd.54604.log)
[filename.robot.54604.log](https://github.com/robocorp/robotframework-lsp/files/9282479/filename.robot.54604.log)

**Comment by ericRobocorp** [comment] 2022-08-08 14:34
That didn't work either.  If I let it sit it will eventually say "Debug adapter timed out waiting for process event." and ask me to open the "launch.json" which I have copied here:
`{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "robotframework-lsp",
            "name": "Robot Framework: Launch .robot file",
            "request": "launch",
            "cwd": "^\"\\${workspaceFolder}\"",
            "target": "^\"\\${file}\"",
            "terminal": "integrated",
            "env": {},
            "args": []
        }
    ]
}`

**Comment by fabioz** [comment] 2022-08-09 11:42
Closing this since the issue is that VSCode itself is not doing the new launch (my guess is that this is happening due to some leftover process -- discussing on slack).

**Closed by fabioz** 2022-08-09 11:42 UTC
Labels: bug, robotframework-ls

**Comment by tantian1498** [comment] 2024-04-12 01:22
> 那也没用。如果我保持静置，它最终会显示“调试等待进程事件超时”。并要求我打开我在此处复制的“launch.json”： `{ // Use IntelliSense to learn about possible attributes. // Hover to view descriptions of existing attributes. // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387 "version": "0.2.0", "configurations": [ { "type": "robotframework-lsp", "name": "Robot Framework: Launch .robot file", "request": "launch", "cwd": "^\"\\${workspaceFolder}\"", "target": "^\"\\${file}\"", "terminal": "integrated", "env": {}, "args": [] } ] }`

samo problem, do you sovle it now?
