### ISSUE TITLE
Running task from embedded "Run" button does not leave browser open with auto_close=FALSE

### ISSUE THREAD

**Issue by orlof** [robocorp/robotframework-lsp#546] opened 2022-01-24 12:52 UTC
When using RPA.Browser.Selenium library it can be imported with auto_close=${FALSE} option.

- If such task is run from inlined "Run" button or from top right corner then the browser is closed after run finishes - the expected behaviour is that browser would be left open.
- Other methods to run the task do leave the browser open: top left run, interactive run, command palette run.

```
*** Settings ***
Library           RPA.Browser.Selenium  auto_close=${FALSE}

*** Tasks ***
Try auto_close
    Open Available Browser  https://robotsparebinindustries.com/
```

**Comment by fabioz** [comment] 2022-01-24 12:57
Closing as this is a duplicate of https://github.com/robocorp/robotframework-lsp/issues/358 (reopened that one).

**Closed by fabioz** 2022-01-24 12:57 UTC
Labels: bug, robocorp-code
