### ISSUE TITLE
Keywords defined in static custom libraries in Python classes are marked "RED" as "Undefined Keyword"

### ISSUE THREAD

**Issue by UnexpectedGrit-3853** [robocorp/robotframework-lsp#522] opened 2021-12-10 21:20 UTC
**Describe the bug**
Robot Framework allows custom Test libraries to be implemented as Python modules and Python classes.
The simplest approach (known as a Static API) is having a module (in Python) with just function definitions or a class (in Python) with class method definitions which map directly to keyword names.
( See 4.1.1 here: http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#id260 )

The bug IS seen if a custom Test Library implements a new Keyword using a Python class, and then a   *.resource   file attempts to use that new Keyword.  The new Keyword inside the   *.resource   will be "Underlined in Red".  If you move your mouse cursor to hover over the new Keyword underlined in Red you'll see, "Undefined keyword: <your-new-keyword-here>".  This will occur even if you make sure under the  *** Settings ***  you have recorded  "Library   <custom-path>/<custom-test-library>"

Conversely, the bug IS NOT seen if a custom Test Library implements a new Keyword using the Python module approach
(e.g.   def my_new_keyword()   ), where all new Keywords are defined as functions in a Python file/module.  The Python file/module has no classes, just functions.  This seems to hold true also as you again make sure under  *** Settings ***  you have recorded  "Library   path-to/my-library.py"

**To Reproduce**
Steps to reproduce the behavior (Windows 10):
1. Create the following directories:   c:\rf-LS-test;   c:\rf-LS-test\Resources;  c:\rf-LS-test\Tests;  c:\rf-LS-test\TestData;  c:\rf-LS-test\Results;  c:\rf-LS-test\Libraries; 
2. Create a new PyCharm Robot Framework project using the above directories
3. In c:\rf-LS-test\Libraries create the file   lib_ble.py    to contain something like

```
from robot.api.deco import keyword


class SaberAsyncBLE(object):
    """
    Saber Async BLE library.
    """
    @keyword(name='Send BLE',
             tags=['lib_ble'])
    def send_ble(self):
        """
        Send a json command to saber over ble

        Returns:
            result(str): device results
        """
        return "something"
```

4. Now in    c:\rf-LS-test\Resources   create the file   testme.resource   to contain  

```
*** Settings ***
Library   ../Libraries/lib_ble.py

*** Variables ***

*** Keywords ***
BLE Unlock
    [Documentation]   Unlocks sync and async BLE channels requires pin to be set
    ${resp}   Send BLE
```

5. You can go ahead and close the PyCharm project and reopen it to see if there are any different results, but my experience was to always see custom Keyword   "Send BLE"  underlined in RED and declared, "Undefined keyword: Send BLE"
6. Now try this. Go to file "lib_ble.py" and replace the file contents with the following

```
from robot.api.deco import keyword


@keyword(name='Send BLE',
         tags=['lib_ble'])
def send_ble():
    """
    Send a json command to device over ble

    Returns:
        result(str): device results
    """
    return "something"
```

7. Close the PyCharm project and the reopen PyCharm project.
8. Now go visit the   "testme.resource"   file.  My experience is that in file   c:\rf-LS-test\Resources\testme.resource    I'll see the custom Keyword  "Send BLE"   is no longer underlined in Red!  Also the new Keyword  "Send BLE" appears to be accepted by the PyCharm system (i.e. the PyCharm gutter is clear!)

**Expected behavior**
New custom Keyword defined by a static custom library containing a Python class and used in a Robot Framework   *.resource   file is properly found and resolved without error.

**Screenshots**

**Versions:**
 - OS: Windows 10
 - Robot Framework Version: 3.8
 - Robot Framework Language Server Version: 0.32.0
 - Client Version: PyCharm 2021.2.3 (Professional Edition)

**Logs**
Add the logs obtained when reproducing the issue.
See: https://github.com/robocorp/robotframework-lsp/blob/master/robotframework-ls/docs/reporting_issues.md for details on how to collect the logs.

Following the above instructions for Log generation, no logs were produced at all.  Perhaps that is because no "Run" was executed.  Everything described in this bug is purely IDE based without having to issue "run" a Robot Frameworks test.
In any event, I checked all the areas suggested by the link and did not discover any log files.

I have attached screen shots showing what I'm experiencing.  I'm hoping that will be helpful.

![custom-library-keyword-func-in-module](https://user-images.githubusercontent.com/86731247/145638674-9932f935-452d-4ed5-b3d5-8dda364cf661.jpg)
![custom-library-keyword-in-class-method](https://user-images.githubusercontent.com/86731247/145638676-f2720f24-43aa-4467-8bf1-fed1503f8361.jpg)
![resource-keyword-bad](https://user-images.githubusercontent.com/86731247/145638678-9c854634-4da1-475b-8f30-fdee5aca52c3.jpg)
![resource-keyword-good](https://user-images.githubusercontent.com/86731247/145638681-bfe7e4eb-f50e-48fb-8d35-4be73db5207f.jpg)

**Comment by fabioz** [comment] 2021-12-10 21:31
Please see: https://github.com/robocorp/robotframework-lsp/blob/master/robotframework-ls/docs/reporting_issues.md#intellij-logs for getting the logs (with instructions specific to Intellij).

Also, you may want to read the FAQ related to this: https://github.com/robocorp/robotframework-lsp/blob/master/robotframework-ls/docs/faq.md#how-to-proceed-if-keywords-from-a-library-are-not-being-resolved

**Comment by UnexpectedGrit-3853** [comment] 2021-12-10 22:22
@fabioz I've checked again, and I've again followed the instructions from   https://github.com/robocorp/robotframework-lsp/blob/master/robotframework-ls/docs/reporting_issues.md#intellij-logs  and again no log files were produced.
I've read the FAQ  https://github.com/robocorp/robotframework-lsp/blob/master/robotframework-ls/docs/faq.md#how-to-proceed-if-keywords-from-a-library-are-not-being-resolved    Good information, but sadly, I found it not to apply to my case.
Please try my included example using Robot Framework Language Server and IntelliJ. I'm interested to hear what your experience will be with Custom Python Libraries using Class methods to define Keywords in PyCharm or IntelliJ

**Comment by fabioz** [comment] 2021-12-11 10:51
@UnexpectedGrit-3853 can you attach a .zip with your sample project where you're reproducing this?

**Comment by fabioz** [comment] 2021-12-13 11:25
I was just rechecking your code and as far as I can tell, the issue is that you're doing a `SaberAsyncBLE` class inside of a `lib_ble.py` -- even when trying to run `Robot Framework` this fail for me.

If you want to have a class the name of the module must be the same.

i.e.: you need to create a `SaberAsyncBLE.py` with a `class SaberAsyncBLE` to use that import, otherwise it doesn't work (even for `Robot Framework`) or you need to import up to the class name (something as `Library    ./lib_ble.MyLib`). Given that, as far as I can tell, the behavior is correct and the language server is properly notifying you of that.

i.e.: from: http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#creating-test-library-class-or-module

`
Python classes are always inside a module. If the name of a class implementing a library is the same as the name of the module, Robot Framework allows dropping the class name when importing the library. For example, class MyLib in MyLib.py file can be used as a library with just name MyLib. This also works with submodules so that if, for example, parent.MyLib module has class MyLib, importing it using just parent.MyLib works. If the module name and class name are different, libraries must be taken into use using both module and class names, such as mymodule.MyLibrary or parent.submodule.MyLib.
`

So, I'm closing as things seem to be working properly for me. If you believe this isn't the case, please reopen.

**Closed by fabioz** 2021-12-13 11:25 UTC
Labels: bug, robotframework-ls
