### ISSUE TITLE
Linter finds undefined variable stored in .py files but those are actually defined and accessible during test case execution

### ISSUE THREAD

**Issue by Franz333** [robocorp/robotframework-lsp#628] opened 2022-03-30 12:49 UTC
**Describe the bug**
I have a "classes.py" file in which I have defined a class that allows me to instantiate Objects responsible to store xpaths.
I have several .py files where I import that class and instantiate objects to store element's xpath.
I am then able to call those objects and access xpath in all of my keywords.txt files. 
The intellisense is showing red squigglies for all those objects. 
Nevertheless when I execute test cases it works well. 

Could be similar to this issue, I dunno https://github.com/robocorp/robotframework-lsp/issues/522

**Expected behavior**
No red squigglies for those objects and no messages "Undefined variable: xxx.xxxxxxx.xxxxx" in VsCode Problems Tab

**Versions:**
- OS: Windows 10 Professionnel - 21H2
- Robot Framework Version: 4.1.3
- Robot Framework Language Server Version: v0.43.2
- Python 3.7.6
- VSCode 1.65.2

**Logs**
The Output Tab in VsCode is not displaying any message. It's blank...

**Comment by fabioz** [comment] 2022-03-30 18:44
@Franz333 can you provide sample code to reproduce the issue?

Also, you may want to check https://github.com/robocorp/robotframework-lsp/blob/master/robotframework-ls/docs/faq.md#how-to-deal-with-undefined-variables for how to deal with undefined variables in general...

**Comment by Franz333** [comment] 2022-03-31 10:19
@fabioz thanks for the support

here is a sample code as requested
[robot-ls.zip](https://github.com/robocorp/robotframework-lsp/files/8387818/robot-ls.zip)

The problem is coming from the linter that false positively indicates that the variables are undefined..

Those variables are actually xpath stored in my Toto.py file
![image](https://user-images.githubusercontent.com/15931812/161032632-fefc5db4-93c6-41b3-ba55-959073ae6a70.png)

Once again, the test case is executed successfully so it has to do with the static analysis..

Thank you for the link to the documentaton.. still please note that my project have worked fine with that structure for the past 10 months until I ran into problems a few days ago.

Given my sample could you tell where to define that "robot.variables" (settings.json?) 
Should it be something in the like? 

 "robot.variables": {
         "Project": "C:\\Users\\roberto.baggio\\Desktop\\robot-ls\\Project\\lib",
 }

Thank you

**Comment by fabioz** [comment] 2022-03-31 10:44
Your project still runs fine, the only thing is that now you're having false positives from the newly added heuristic regarding undefined variables.

In this case the language server really can't find them because it doesn't follow imports (so, your structure is too dynamic for the static analyzer).

i.e.: your structure is something as:

Robot file:
```
*** Settings ***
Variables       lib/GUI_data.py
```

`lib/GUI_data.py`
```
from Toto import *
```

`lib/Toto.py`:
```
main = Page()
```

With this structure you can either change the robot file to directly import `lib/Toto.py`.

i.e.:

```
*** Settings ***
Variables       lib/Toto.py
```

Or you can ask the linter to ignore that variable with a setting such as:

`"robot.lint.ignoreVariables": ["main"]`.

Or disable the undefined variables linting altogether with: `"robot.lint.variables": false`.

**Comment by fabioz** [comment] 2022-03-31 10:45
Note: as it is this is a duplicate of https://github.com/robocorp/robotframework-lsp/issues/630, so, I'm closing this one (you should be able to use one of the workarounds in the comment above: https://github.com/robocorp/robotframework-lsp/issues/628#issuecomment-1084407328).

**Closed by fabioz** 2022-03-31 10:45 UTC
Labels: bug, robotframework-ls

**Comment by Franz333** [comment] 2022-03-31 12:15
Hi @fabioz 

Thank you for the support once again.

I could directly import as you mentioned but the idea of having an intermediate file that does the import is more convenient to use when working with several robot files

`"robot.lint.ignoreVariables": ["main"]` is not an option as I have many objects to declare and the list is increasing as I automate new projects..

`"robot.lint.variables": false` is not an option either as it is a really useful tool to use

I will downgrade to version v0.42.0 as it appears to be working as a charm

Thank you very much

**Comment by fabioz** [comment] 2022-03-31 12:22
Version `0.42.0` doesn't analyze variables at all (so, by downgrading you're effectively doing the same as: `"robot.lint.variables": false`).

As a note, instead of having a single `.py` file where you import everything, you could have a single `.robot` file which imports many `.py` files (the imports aren't followed on the Python side but they are followed in the robot side).

**Comment by fabioz** [comment] 2022-03-31 12:25
@Franz333 note that we're just talking about the linting of `undefined variables` here (the linting will still happen and it'll analyze other things such as undefined keywords...).

**Comment by Franz333** [comment] 2022-03-31 12:32
@fabioz yes you are right, I should consider it cause after a quick retry 0.42.0 is actually not a solution :-D
