### ISSUE TITLE
Support navigating to a variable located in a YAML file

### ISSUE THREAD

**Issue by lynhbn** [robocorp/robotframework-lsp#679] opened 2022-05-16 09:38 UTC
**Is your feature request related to a problem? Please describe.**
Currently we cannot navigate to a variable ${a} located in a YAML file

**Describe the solution you'd like**
Support navigating to a variable located in a YAML file after declaring `Variable    ./sample.yaml`

**Comment by fabioz** [comment] 2022-05-16 12:09
I can't reproduce this in a simple example. Can you attach a sample project where this issue can be reproduced?

**Comment by fabioz** [comment] 2022-07-10 10:58
Closing since no additional info was given (and it's possible to navigate to `.yaml` files in the current version of the language server).

Please reopen if you're able to provide some sample code showing the issue.

**Closed by fabioz** 2022-07-10 10:58 UTC
Labels: enhancement, robotframework-ls
