### ISSUE TITLE
High CPU load when Language Server is integrated in VSCode

### ISSUE THREAD

**Issue by cafe88** [robocorp/robotframework-lsp#354] opened 2021-05-17 07:18 UTC
Robot framework language server in VSCode is using very much CPU power in idle.
May be the same error as mentioned in #350

**To Reproduce**
Install Robot Framework Language
Reload VSCode
Open a .robot file.

**Expected behavior**
No significant change in processor activity should happen when sitting idle.

**Screenshots**
![image](https://user-images.githubusercontent.com/3005937/118445786-2cccf280-b6ef-11eb-9e0f-0d7c848c3c29.png)

**Additional Information** (from `code --status`, shortened)
```
CPU %   Mem MB     PID  Process
    5       23   20196           C:\Users\mweinberg\AppData\Local\Programs\Python\Python38\python.exe -u c:\Users\mweinberg\.vscode\extensions\robocorp.robotframework-lsp-0.16.0\src\robotframework_ls\__main__.py -vv --log-file=~/robotframework_ls.log
    8       34   16792           C:\Users\mweinberg\AppData\Local\Programs\Python\Python38\python.exe -u c:\Users\mweinberg\.vscode\extensions\robocorp.robotframework-lsp-0.16.0\src\robotframework_ls\server_api\server__main__.py -vv --log-file=~/robotframework_ls.log.lint.api
    7       33   23756           C:\Users\mweinberg\AppData\Local\Programs\Python\Python38\python.exe -u c:\Users\mweinberg\.vscode\extensions\robocorp.robotframework-lsp-0.16.0\src\robotframework_ls\server_api\server__main__.py -vv --log-file=~/robotframework_ls.log.1.others.api
```

**Logs:**
If logs are needed, i can add them here.
But then I'll have to check it before posting because this is an issue which happens on my PC at work.

**Versions:**
OS: Windows 10
Robot Framework Language Server: 0.16.0
VSCode: 1.56.2

**Comment by fabioz** [comment] 2021-05-17 17:37
This really seems like a duplicate of https://github.com/robocorp/robotframework-lsp/issues/350, so, I'm going to close this one.

Note: I added comments at: https://github.com/robocorp/robotframework-lsp/issues/350#issuecomment-842506969 so that I can get some further information to know what's actually going on... if you can provide those from your machine and attach it to that issue, that'd be nice.

**Closed by fabioz** 2021-05-17 17:37 UTC
