### ISSUE TITLE
[Intellij] Document becomes unsynchronized with language server

### ISSUE THREAD

**Issue by eduardfarkas** [robocorp/robotframework-lsp#372] opened 2021-05-27 12:29 UTC
**Describe the bug**
(Not sure if it doesn't belong under issue https://github.com/robocorp/robotframework-lsp/issues/365)

**Sometimes** on document change colors of nearly every element are shifted somehow and suggestions are wrong too.
Closing and reopening the file helps.

Happening since 0.17.0

**To Reproduce**
1. In intellij IDEA delete some resources

**Expected behavior**
Preserve syntax hihglighting and suggestions

**Screenshots**
deleting something:
https://gyazo.com/5b66dc0d21bf200693646aab94b62102

ctrl+z on the same file
https://gyazo.com/0c95d9227cc7b4869a02ccdd2ecd5fc0

suggestions
https://gyazo.com/c6e86365e75bed6e1159f4153d10f091

**Versions:**
 - OS: w10
 - Robot Framework Version 4.0.2
 - Robot Framework Language Server Version 0.17.0
 - Client Version IntelliJ IDEA 2021.1.1

**Logs**
Add the logs obtained when reproducing the issue.
See: https://github.com/robocorp/robotframework-lsp/blob/master/robotframework-ls/docs/reporting_issues.md for details on how to collect the logs.

**Comment by fabioz** [comment] 2021-05-27 12:55
This seems to be a different issue (so, it should really be separate).

Does any error appear on the client side (Intellij) when that happens?

Can you share the logs following the instructions from https://github.com/robocorp/robotframework-lsp/blob/master/robotframework-ls/docs/reporting_issues.md when that happens?

**Comment by eduardfarkas** [comment] 2021-05-27 13:17
I am not really able to reproduce this. It works correctly now. It happened like 4 times maybe. 
There wasn't any error message at the time.

Here are logs from intellij start up
[robotframework_ls.remote_fs_observer.15964.log](https://github.com/robocorp/robotframework-lsp/files/6554259/robotframework_ls.remote_fs_observer.15964.log)
[robotframework_ls.lsp.19816.log](https://github.com/robocorp/robotframework-lsp/files/6554264/robotframework_ls.lsp.19816.log)

**Comment by fabioz** [comment] 2021-05-31 14:38
Not having the logs when this actually happens makes it pretty difficult to diagnose...

Apparently, what's happening is that the document in the Intellij side looses the synchronization with the document on the language server side.

I was thinking that this could happen if a timeout in the document change is received, so, I just provided a fix which could potentially fix that (but given that I can't really reproduce this, it's still possible that this isn't enough).

Also, a question: how often do you see this happening?

Also, do you have any non-empty `.log` file in: `%userprofile%/.robotframework-ls`? If you do, can you attach them to this issue?

**Comment by fabioz** [comment] 2021-05-31 14:39
Reopening as I'm still waiting for more info...

**Comment by fabioz** [comment] 2021-06-02 17:53
Ok, closing since there was no further info provided (@eduardfarkas but if you can provide the non-empty `.log` files you may have in: `%userprofile%/.robotframework-ls`, later on, please do so -- if that's the case it's possible that I haven't really targeted the root cause here)...

**Closed by fabioz** 2021-06-02 17:53 UTC
Labels: bug, robotframework-ls

**Comment by eduardfarkas** [comment] 2021-06-03 09:08
For past few days the issue did not occur. If it happens again i will contact you
