### ISSUE TITLE
Environment variable is not getting resolved in custom Python library

### ISSUE THREAD

**Issue by oferdan** [robocorp/robotframework-lsp#568] opened 2022-02-09 13:31 UTC
**Describe the bug**
I have a custom Python library that is using BuiltIn().get_variable_value() to get an environment variable stored in variables.yaml file and I'm using this variable in this custom library, but the variable is not resolved.

**To Reproduce**
Have variable file _**variables.yaml**_
```
config_PROXY:    127.0.0.1
```

Have custom Python library _**driversync.py**_ and call BuiltIn().get_variable_value() 
```
from robot.libraries.BuiltIn import BuiltIn
proxy = BuiltIn().get_variable_value("${config_PROXY}")
```

Import this custom Python library in Robot resource file _**driverutil.robot**_
```
Library   ../libraries/driversync.py
Variables  variables.yaml
```

**Expected behavior**
The environment variable is correctly resolved for the Libspec generation within RobotFramwork LSP.

**Versions:**
 - OS: Windows 10
 - Robot Framework Version: 4.1.1 (Python 3.7.3 on win32)
 - Robot Framework Language Server Version: 0.39.0
 - Client Version: VSCode 1.64.1

**Logs**

```
Traceback (most recent call last):
File "c:\Users\oferdan\.vscode\extensions\robocorp.robotframework-lsp-0.39.0\src\robotframework_ls\impl\libspec_manager.py", line 898, in _cached_create_libspec cwd=cwd,

File "c:\Users\oferdan\.vscode\extensions\robocorp.robotframework-lsp-0.39.0\src\robotframework_ls\impl\libspec_manager.py", line 786, in _subprocess_check_output
return subprocess.check_output(*args, **kwargs)

File "C:\Users\oferdan\AppData\Local\Programs\Python\Python37-32\lib\subprocess.py", line 395, in check_output **kwargs).stdout

File "C:\Users\oferdan\AppData\Local\Programs\Python\Python37-32\lib\subprocess.py", line 487, in run output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['C:\\Users\\oferdan\\AppData\\Local\\Programs\\Python\\Python37-32\\python.exe', '-m', 'robot.libdoc', '-P', 'c:\\Users\\oferdan\\Git\\hs-classic-automation\\libraries', 'driversync', 'C:\\Users\\oferdan\\.robotframework-ls\\specs\\v2\\a57ee226_4.1.1\\user\\c7d3dc9d.libspec']' returned non-zero exit status 252.
lsp: 2022-02-09 13:17:48 UTC pid: 19524 - ThreadPoolExecutor-0_0 - INFO - robotframework_ls.robotframework_ls_impl
Cancelled handling: <function RobotFrameworkLanguageServer._async_api_request at 0x03137108>

lsp: 2022-02-09 13:18:14 UTC pid: 19524 - ThreadPoolExecutor-0_0 - INFO - robotframework_ls.robotframework_ls_impl
Cancelled handling: <function RobotFrameworkLanguageServer._async_api_request at 0x03137108>

server-api: 2022-02-09 13:18:20 UTC pid: 24688 - ThreadPoolExecutor-0_2 - EXCEPTION - robotframework_ls.impl.libspec_manager
Error creating libspec: driversync.
Return code: 252
Output:
Importing library 'driversync' failed: RobotNotRunningError: Cannot access execution context

Traceback (most recent call last):
File "c:\Users\oferdan\Git\hs-classic-automation\libraries\driversync.py", line 20, in <module>
proxy = BuiltIn().get_variable_value("${config_PROXY}")

File "C:\Users\oferdan\AppData\Local\Programs\Python\Python37-32\lib\site-packages\robot\libraries\BuiltIn.py", line 1539, in get_variable_value
name = self._get_var_name(name)

File "C:\Users\oferdan\AppData\Local\Programs\Python\Python37-32\lib\site-packages\robot\libraries\BuiltIn.py", line 1805, in _get_var_name
replaced = self._variables.replace_string(original)

File "C:\Users\oferdan\AppData\Local\Programs\Python\Python37-32\lib\site-packages\robot\libraries\BuiltIn.py", line 78, in _variables
return self._namespace.variables

File "C:\Users\oferdan\AppData\Local\Programs\Python\Python37-32\lib\site-packages\robot\libraries\BuiltIn.py", line 74, in _namespace
return self._get_context().namespace

File "C:\Users\oferdan\AppData\Local\Programs\Python\Python37-32\lib\site-packages\robot\libraries\BuiltIn.py", line 69, in _get_context
raise RobotNotRunningError('Cannot access execution context')
```

Might be similar issue like in https://github.com/robocorp/robotframework-lsp/issues/535

**Comment by fabioz** [comment] 2022-02-12 13:04
The problem isn't even that the variable isn't being resolved, the problem is that during libspec generation time, a robot isn't really running -- the module/class is imported and then introspected to generate the information.

So, the workaround for now is doing something as:

```
try:
    proxy = BuiltIn().get_variable_value("${config_PROXY}")
except RobotNotRunningError:
    return  # The robot is not currently running (it's probably imported only to generate a `.libspec`).
```

A "real" fix for this would be not doing introspection to generate the libspec (just work with the Python AST), but this is a huge undertaking (because resolving what's a keyword without doing introspection is really hard in a dynamic language as Python)... This might be done in the future, but as there aren't plans to do it in the short/mid term I'm closing this issue (i.e.: this is already a known issue).

**Closed by fabioz** 2022-02-12 13:04 UTC
Labels: bug, robotframework-ls
