### ISSUE TITLE
*** settings *** section in start of a file throws a Mutex error

### ISSUE THREAD

**Issue by pZq** [robocorp/robotframework-lsp#733] opened 2022-08-22 07:58 UTC
**Describe the bug**

In VS CODE -> .robot or .resource files with a *** settings *** section in start of a file throws this error for me.
**Error collecting Robocop errors: Unable to get mutex for: c:\users\user\.robotframework-ls\specs\v2\769da057_5.0.1\builtins\xml.libspec after 30 seconds.**

![image](https://user-images.githubusercontent.com/6633097/185843392-ef2c070d-3dfa-4806-a4b7-bd20b9b8ee96.png)

At some point it seemed like the error went away when i deleted Documentation from *** settings *** section but after a while the error returned.

Is it missconfiguration of VS code and if so, please suggest what setting i should be looking for to fix it ?
I understand mutex is some kind of multithreading but thats all i understand about mutex :)

I use also TFS checkout extension and the files i have open in the folder view are all in a TFS folder -> Just in case, if that would lead to some sort of problems... But the TFS sync folder is not the one the error states so i think TFS extension is not the issue in this case.

I tried also to give permissions for that builtin folder for everyone and full permissions but that didn't help either.

**To Reproduce**
Just install LSP extension in VS code and make a *** settings *** section, maybe some testcase needs to be also be built just some simple.

**Expected behavior**
---> I think mutex problem should not be seen.

**Screenshots**
Screenshot in description.

**Versions:**
I use
Windows 10 pro 10.0.19043 
VS Code 1.70.2
Python 3.10.6 on win32
Robot framework version v5.0.1
VS extension → Robot framework language server v.1.0.0 → last updated 17.8.2022 (17th of august).

**Logs**
Error collecting Robocop errors: Unable to get mutex for: c:\users\user\.robotframework-ls\specs\v2\769da057_5.0.1\builtins\xml.libspec after 30 seconds.

**Comment by fabioz** [comment] 2022-08-22 11:46
Can you provide the full output you have (in `OUTPUT > Robot Framework`) when this error happens?

Note that the problem isn't really the `***Settings***` section per se, rather collecting information from the `xml` module in your machine seems to be slow (you see a mutex error because the language server spawns multiple processes that may request the same info, but when one starts computing that info it create a file-mutex and the other process has to wait for that process to finish and it didn't finish after 30 seconds...).

As a note, it's possible that in your scenario with TFS things are really slow, so, maybe the only solution would be raising that timeout...

**Comment by pZq** [comment] 2022-08-22 12:14
Ok, thanks. I can try to get rid of TFS extension and use a separate folder to see if i can get around this problem.

There is also many things i must filter out from the log before i can publish it here so -> let me first try to get rid of the TFS folder. I will return when i have tested without TFS so that i can confirm, if its an TFS related issue or something else.

**Comment by fabioz** [comment] 2022-08-22 17:51
This was fixed in: https://github.com/robocorp/robotframework-lsp/commit/9faffec32578a0c3d8b03c21e12ba8fe39a735de

I've just pushed a `1.0.7` pre-release. Can you test if it works for you? 

-- note: it may take some more minutes for it to appear in the VSCode marketplace.

**Closed by fabioz** 2022-08-22 17:51 UTC
Labels: bug, robotframework-ls

**Comment by pZq** [comment] 2022-08-23 07:59
1.0.7 version seems to fix the mutex error.

NICE WORK! Thanks!


ma 22. elok. 2022 klo 20.51 Fabio Zadrozny ***@***.***)
kirjoitti:
