### ISSUE TITLE
Color Scheme breaks when adding backslash in named argument

### ISSUE THREAD

**Issue by ferroiz** [robocorp/robotframework-lsp#649] opened 2022-04-13 09:48 UTC
While calling a keyword, if you add a backslash in any named argument, the color scheme breaks and all the syntax highlighting becomes white (only variables seems not affected to this).

I'm attaching two screenshot to explain better.
![backslash-broken-color-scheme](https://user-images.githubusercontent.com/82469806/163150299-ed49815b-2469-4a4d-a72b-ec5c728a6af3.png)
![working-color-scheme](https://user-images.githubusercontent.com/82469806/163152008-e8c82500-046a-4581-bedd-cfc4030a66c2.png)

(nothing related to lsp is logged in intellij files and no logs from lsp are reported)

**Comment by fabioz** [comment] 2022-04-13 10:17
Thanks for the report. This is actually a duplicate of https://github.com/robocorp/robotframework-lsp/issues/647 (which was already fixed).

I'll probably create a new release later today due to that.

**Closed by fabioz** 2022-04-13 10:17 UTC

**Comment by ferroiz** [comment] 2022-04-13 10:19
Perfect, thanks!
(didn't check the closed ones sry)
