### ISSUE TITLE
Code completion breaks if you pass an argument into the Library call in pycharm

### ISSUE THREAD

**Issue by alvovsky** [robocorp/robotframework-lsp#538] opened 2022-01-14 16:59 UTC
`Library        GoogleCommand       ${var}        `
Fails to find the library for code completion but runs fine.

`Library        GoogleCommand`
Works fine.
 

**Versions:**
 - OS: [Windows 10]
 - Robot Framework 4.1.1 (Python 3.9.7 on win32)
 - Robot Framework Language Server Version: [0.35.0]
 - Client Version: [PyCharm 2021.3.1]

**Comment by fabioz** [comment] 2022-03-14 23:40
Sorry about the delay in getting back to you... The latest releases had changes on how arguments are dealt with, can you check with the latest version to check if it's working for you now?

If it's still not working, can you give more details? Is this a library from pip? Can you provide a link for me to install it myself?

**Comment by jkRobotic** [comment] 2022-03-19 08:12
Hi, I think the bug is about the libraries which accepts arguments beside alias names. The bug wasn't posted by me, but I'm also interested in this bug.

I think the GoogleCommand library doesn't exist on pip, so I created a very simple library and attached into this comment.

The bug:
 When a Library called, its hint will show that accepts arguments, but they won't be used.

Pictures about using the TestLib library (I know the bug is for Pycharm, but it can be reproduced in VSCode).

Robot file with Library loading and a simple testcase - because the generation doesn't work, the keywords are undefined:
![image](https://user-images.githubusercontent.com/87384643/159112991-083814e7-6b1c-4b25-8209-fe6b6324ee88.png)

Keyword list if CTRL+SPACE pressed on alias names - it doesn't find the generated keyword:
![image](https://user-images.githubusercontent.com/87384643/159113058-19c0ed3b-8cad-4509-ada4-ada045ec1fe6.png)

The test will run smoothly and recognize the passed parameters:
![image](https://user-images.githubusercontent.com/87384643/159113089-3d9042cd-6f78-4e85-8075-3c15d82a8c6f.png)

Already mentioned this option in #397, but there the focus was on the alias names. (The alias topic is solved, and sorry I missed to thank you).

I think the major issue is with the load of libraries what will generate their keywords during the load, like the example above.

The test library is in the attachment (it is really simple), and feel free to ask. You can find the usage in ReadMe.md.
[TestLib.zip](https://github.com/robocorp/robotframework-lsp/files/8308820/TestLib.zip)

Thank you in advance!

**Comment by fabioz** [comment] 2022-03-19 11:10
@jkRobotic that's a different issue.

This happens because by default it'll not pass arguments to the library when collecting keywords (because usually libraries don't have different keywords based on the arguments).

If that's required, you must ask the language server to do that by using the `robot.libraries.libdoc.needsArgs` setting.

The faq has more info related to that: https://github.com/robocorp/robotframework-lsp/blob/master/robotframework-ls/docs/faq.md#how-to-proceed-if-keywords-from-a-library-are-not-being-resolved

**Comment by jkRobotic** [comment] 2022-03-19 15:34
@fabioz  you are right, I didn't notice this section in FAQ. Thanks for the info, with the example lib above it worked.

I still notice that it won't work if the list is from a file (txt for example). But this will be described in a different enhancement.

Thanks again!

**Comment by fabioz** [comment] 2022-03-20 11:59
Closing this as variables are resolved now (and it's possible to pass arguments to the library generation following the steps at: https://github.com/robocorp/robotframework-lsp/blob/master/robotframework-ls/docs/faq.md#how-to-proceed-if-keywords-from-a-library-are-not-being-resolved).

@alvovsky if you still can't get it to work, please reopen the issue adding additional information on the actual library and how it's structured.

**Closed by fabioz** 2022-03-20 11:59 UTC
Labels: bug, robotframework-ls, P0, waiting for info
