### ISSUE TITLE
Variables autocomplete only works when they are inside quotes

### ISSUE THREAD

**Issue by JoneSabino** [robocorp/robotframework-lsp#54] opened 2020-04-25 21:50 UTC
The autocomplete for variable names only work if we pass the argument in-between "" as shown below:

![image](https://user-images.githubusercontent.com/21135355/80291494-46864b00-8724-11ea-8e10-868487e252aa.png)

When you type the variable without quotes it doesn't suggest anything.

Also, I'd like to suggest a smarter autocomplete for variables, that search for the variables names that we declared and when it comes do dicts, suggest only the keys of that specific dict and so on.

Today's autocomplete for variables when it works,  seems to be more like getting all the words typed in the file that matches my current typing.

**Comment by Snooz82** [comment] 2020-04-25 22:44
Currently there is NO auto completion for variables implemented in LSP.
What you see, is VSCode suggesting words it has found in already existing code.

Variable completion is not that easy. But there are already discussions about implementing an easy completion based on static parsing. Like variables section, keywords arguments and variable assignments from keywords return values.

But it is not yet done!

**Comment by Snooz82** [comment] 2020-04-25 22:44
You see the state in #21

**Comment by fabioz** [comment] 2020-04-26 11:00
As commented, this is not done, you're really only getting word completions. 

Closing this as a duplicate of https://github.com/robocorp/robotframework-lsp/issues/21.

**Closed by fabioz** 2020-04-26 11:00 UTC
