### ISSUE TITLE
Pycharm with LSP-support plugin: Intellisense is case sensitive

### ISSUE THREAD

**Issue by Pakkanen1** [robocorp/robotframework-lsp#86] opened 2020-06-08 07:28 UTC
I have setup LSP on pycharm using the longer instuctions here: https://forum.robotframework.org/t/pycharm-with-lsp/161/2

Whenever I try to make a request for code completion without a capital first letter, pycharm says "no suggestions". Doing the same with a capital first letter will produce a suggestion list of valid keywords.
**Versions:**
Pycharm 2020.1.1 community
robotframework 3.2.1
robotframework-lsp 0.2.1
seleniumlibrary 4.4.0
windows 10 pro
LSP support plugin 1.6.1

----------------------------------------------
Log:
[robotframework_lsrob.lsp.16696.log](https://github.com/robocorp/robotframework-lsp/files/4744454/robotframework_lsrob.lsp.16696.log)
Log 2 (API-file):
[robotframework_lsrob.log.lsp.txt](https://github.com/robocorp/robotframework-lsp/files/4744465/robotframework_lsrob.log.lsp.txt)

----------------------------------------------

Example:
----------------------------------------------
1. Created a new folder with "test2.robot" file.
2. Made library import in settings section and created test case section
3. Wrote test case name
4. Closed pycharm, deleted logs
5. Opened pycharm
6. wrote "wait" inside the test case and tried code completion with CTRL+SPACE
![image](https://user-images.githubusercontent.com/5936882/84003262-69865a80-a972-11ea-9d37-2221fefba240.png)
7. Closed pycharm

**Comment by fabioz** [comment] 2020-06-08 11:14
I took a look at the logs and the completions seem to be correct. So, the issue is not in the language server, but rather in the lsp client (so, I'm closing the issue here as there's not much to be done on the language server).

**Closed** 2020-06-08 11:15 UTC
