### ISSUE TITLE
Debug Robot Framework Browser without a RCC-managed environment

### ISSUE THREAD

**Issue by fdaguin** [robocorp/robotframework-lsp#436] opened 2021-08-28 12:39 UTC
**Is your feature request related to a problem? Please describe.**
The current way of debugging Robot Framework Browser (as documented [here](https://robocorp.com/docs/development-guide/browser/how-to-debug-playwright-robots-in-visual-studio-code)) requires a Conda environment, as defined in `conda.yaml`.

**Describe the solution you'd like**
I'd like to access this debug feature by relying on my own virtual environment managed with Poetry.

I do understand the strong integration with RCC here. However, I think this feature could benefit to non-RCC users. To that extent, could this debug feature maybe be ported into the Language Server?

**Describe alternatives you've considered**
Only debugging with the Language Server. However, the features are limited:

- even if running in non-headless mode, no browser is opening
- there is no debug console

**Comment by fabioz** [comment] 2021-08-30 10:51
Hello and thank you for your suggestion. 

As you noted, you can just use the language server directly and configure the python interpreter that you want to use there (i.e.: just point the python from the poetry env in the language server configuration).

Regarding the features:
>  even if running in non-headless mode, no browser is opening
>  there is no debug console

This is an issue in your environment -- you can surely get the browser to open / use the debug console even if not using a robot environment.

If it's not working for you, it's a problem in your environment and the fact that it works with a robot environment just means that your poetry environment is not properly configured... 

Getting things ready from `pip` as poetry does is definitely more difficult than getting things ready from `conda` and that's mostly out of the scope of the language server -- as a note, if you get it to work in a terminal and it's not working in the language server, please create an issue so that I can guide you on reproducing the env from the terminal into the language server, but if it's not even working in the terminal then it's expected that won't work in the language server either.

So, I'm closing because I don't think I'll have the time to do it myself (this would be too low priority and I'm not really fond of leaving items I don't think will be tackled open), but if you'd like to provide a pull request for the feature it can be reopened...

**Closed by fabioz** 2021-08-30 10:51 UTC
Labels: enhancement, robocorp-code

**Comment by fdaguin** [comment] 2021-08-30 11:19
Thanks a lot for this feedback @fabioz, this was definitely helpful: I managed to resolve my issues 😄
