### ISSUE TITLE
keywords underlined when holding ctrl don't underline the whole keyword

### ISSUE THREAD

**Issue by DetachHead** [robocorp/robotframework-lsp#499] opened 2021-11-09 22:45 UTC
**Describe the bug**
when you hold ctrl and hover over a keyword with spaces in it, only the word you're hovering over is underlined.

**To Reproduce**
1. Open/create a `.robot` file with a test case calling a keyword with spaces in its name
2. hold ctrl key (or whatever key it is on mac) and hover over the keyword

**Expected behavior**
entire keyword `some keyword` is underlined instead of just `some` or `keyword`

**Screenshots**
![image](https://user-images.githubusercontent.com/57028336/141017022-30864940-876f-41ea-a456-c51bb8d157fe.png)

**Versions:**
 - OS: windows 10
 - Robot Framework Version: 4.1.1
 - Robot Framework Language Server Version: 0.28.0
 - Client Version 1.62.0

**Comment by fabioz** [comment] 2021-11-10 09:55
Closing as this is a duplicate of: https://github.com/robocorp/robotframework-lsp/issues/279

**Closed by fabioz** 2021-11-10 09:55 UTC
Labels: bug, robotframework-ls
