### ISSUE TITLE
Test Teardown Fail shown as sucessful in test explorer

### ISSUE THREAD

**Issue by DanielPenning** [robocorp/robotframework-lsp#892] opened 2023-02-20 09:23 UTC
**Describe the bug**
Tests that fail during test teardown will be shown as sucessful in VS Code test explorer.

**To Reproduce**

1. Add a listener (v3) to some library that always fails during test teardow
```    
def end_test(self, data, result):
    result.passed = False
    result.message = "Failed in test teardown"
```

2. Use the library in at least one test case.

**Expected behavior**
As expected, Robot Framework Log will show the test failed. The test explorer in VS Code shows the test as passed.

**Versions:**
 - OS: Windows 10
 - Robot Framework Version: 4.1.3
 - Robot Framework Language Server Version: v1.9.0
 - Client Version: VS Code 1.75.1

**Comment by fabioz** [comment] 2023-03-06 12:57
@DanielPenning the issue is that events are also gotten with a listener, but now there's an ordering conflict because the listener from the debugger is registered prior to the listener from the library.

This isn't fixable unless RF itself provides a way to provide priorities to listeners.

As a note, this was reported to RF in 2020 (https://github.com/robotframework/robotframework/issues/3473) and it seems like it's scheduled for 6.2.

**Comment by fabioz** [comment] 2023-03-06 12:59
Note: closing issue here. When RF does implement that, you can make your listener have higher priority, so, nothing would be needed in the language server.

**Closed by fabioz** 2023-03-06 12:59 UTC
Labels: bug, robotframework-ls

**Comment by DanielPenning** [comment] 2023-03-06 13:07
@fabioz Thanks for the explanation! Good to know, I will track the RF development for this.
