### ISSUE TITLE
Error collecting robocop errors in resource file

### ISSUE THREAD

**Issue by drgarbi** [robocorp/robotframework-lsp#670] opened 2022-04-28 18:16 UTC
**Describe the bug**
An error is thrown at the beginning of the resource file indicating that "Error collecting Robocop errors: ('EOF in multi-line statement', (2, 0)) robotframework"

**To Reproduce**
1. Open the file "System.resource"
2. See error in the beginning of the file and no other robocop info/warnings are shown

**Expected behavior**
No error at the beginning of the file and correct linting of the rest of the file

**Screenshots**
![image](https://user-images.githubusercontent.com/31523452/165820654-3594bd7d-e5dc-47ea-a92c-5bea6671ec02.png)

![image](https://user-images.githubusercontent.com/31523452/165820597-7a155cf0-7ca3-47da-a510-1f69858bbe68.png)

**Versions:**
 - OS: Ubuntu 20.04.4
 - Robot Framework Version: 4.1.3
 - Robot Framework Language Server Version: v0.46.2 (pre-release)
 - Client Version: VSCode 1.66.2

**Logs**
[robotframework_ls_logs.zip](https://github.com/robocorp/robotframework-lsp/files/8585343/robotframework_ls_logs.zip)

**Comment by fabioz** [comment] 2022-04-29 11:58
This seems to be an error in `Robocop` itself and I think there's little to be done in the language server side.

The error is probably parsing something different than what you're showing in the issue (since it's probably a huge file -- the logs don't show the full file due to performance and privacy considerations)... 

I think you can probably delete things in the file until the error goes away to try to do some bisecting to find the actual construct where this happens (or if there aren't privacy considerations there you can also share the full file so that it's possible to find out the cause there).

**Comment by fabioz** [comment] 2022-05-05 17:51
Closing as there wasn't further feedback (and the issue seems to be in `Robocop` anyways...).

**Closed by fabioz** 2022-05-05 17:51 UTC
Labels: bug, robotframework-ls

**Comment by fabioz** [comment] 2022-06-08 10:10
@GLMeece can you reproduce that reliably? Is this some code you could share?

**Comment by GLMeece** [comment] 2022-06-21 21:51
Sorry about the delay here. Actually, after troubleshooting I found out I had left the following line in my `pyproject.toml` file:

```toml
[tool.robocop]
# lots of other rules redacted here
output = "robocop.log"
```

When I commented out that line, my issue went away.
